Repository Escape-Technologies/graphql-armor, pull requests merged in 2022-08, with the labels that each got.

#31 Feat/improved example
  README.md
  examples/apollo/README.md
  examples/apollo/package.json
  examples/apollo/src/index.ts
  examples/apollo/tsconfig.json
  examples/nestjs/README.md
  examples/yoga/README.md
  examples/yoga/package.json
  examples/yoga/src/main.ts
  examples/yoga/src/schema.ts
  examples/yoga/tsconfig.json
  yarn.lock
Labels: documentation

#33 feat: tests pipeline
  .github/workflows/ci.yaml
  .vscode/launch.json
  examples/apollo/.hooks/pre-commit.json
  examples/apollo/package.json
  examples/apollo/src/index.ts
  examples/nestjs/.hooks/pre-commit.json
  examples/nestjs/package.json
  examples/nestjs/src/app.module.ts
  examples/nestjs/src/book/book.model.ts
  examples/nestjs/src/book/book.resolver.ts
  examples/nestjs/tsconfig.json
  examples/yoga/.hooks/pre-commit.json
  examples/yoga/package.json
  examples/yoga/src/main.ts
  examples/yoga/src/schema.ts
  packages/graphql-armor/.hooks/pre-commit.json
  packages/graphql-armor/package.json
  packages/graphql-armor/tsconfig.json
  yarn.lock
Labels: enhancement

#50 Envelop/complexity
  examples/apollo/src/index.ts
  packages/graphql-armor/src/apollo/armor.ts
  packages/graphql-armor/src/apollo/protections/cost-analysis.ts
  packages/graphql-armor/src/config.ts
  packages/graphql-armor/src/envelop/protections/cost-analysis.ts
  packages/graphql-armor/src/validationRules/cost-analysis.ts
Labels: enhancement

#52 chore(armor): remove ignored typing
  packages/graphql-armor/src/validationRules/cost-analysis.ts
  packages/graphql-armor/src/validationRules/max-aliases.ts
  packages/graphql-armor/src/validationRules/max-depth.ts
  packages/graphql-armor/src/validationRules/max-directives.ts
Labels: enhancement

#62 Fix/remove config
  examples/apollo/src/index.ts
  examples/nestjs/src/app.module.ts
  packages/graphql-armor/src/apollo/protections/base-protection.ts
  packages/graphql-armor/src/apollo/protections/character-limit.ts
  packages/graphql-armor/src/apollo/protections/cost-analysis.ts
  packages/graphql-armor/src/apollo/protections/max-aliases.ts
  packages/graphql-armor/src/apollo/protections/max-depth.ts
  packages/graphql-armor/src/apollo/protections/max-directives.ts
  packages/graphql-armor/src/config.ts
  packages/graphql-armor/src/envelop/protections/base-protection.ts
  packages/graphql-armor/src/envelop/protections/character-limit.ts
  packages/graphql-armor/src/envelop/protections/cost-analysis.ts
  packages/graphql-armor/src/envelop/protections/max-aliases.ts
  packages/graphql-armor/src/envelop/protections/max-depth.ts
  packages/graphql-armor/src/envelop/protections/max-directives.ts
  packages/graphql-armor/src/envelop/protections/protection-options.ts
  packages/plugins/block-field-suggestions/src/index.ts
Labels: enhancement, breaking change

#80 feat(plugins): individual cost limit
  .changeset/cold-pens-punch.md
  packages/graphql-armor/package.json
  packages/graphql-armor/src/apollo/armor.ts
  packages/graphql-armor/src/apollo/protections/cost-analysis.ts
  packages/graphql-armor/src/apollo/protections/cost-limit.ts
  packages/graphql-armor/src/config.ts
  packages/graphql-armor/src/envelop/armor.ts
  packages/graphql-armor/src/envelop/protections/cost-analysis.ts
  packages/graphql-armor/src/envelop/protections/cost-limit.ts
  packages/graphql-armor/test/envelop/armor.spec.ts
  packages/plugins/cost-limit/README.md
  packages/plugins/cost-limit/package.json
  packages/plugins/cost-limit/src/index.ts
  packages/plugins/cost-limit/tsconfig.json
  yarn.lock
Labels: dependencies, apollo, envelop

#84 tests/unit-testing
  .changeset/nice-eels-enjoy.md
  .vscode/launch.json
  README.md
  examples/apollo/src/index.ts
  examples/apollo/src/server.ts
  examples/apollo/test/index.spec.ts
  examples/nestjs/package.json
  examples/nestjs/src/book/book.service.ts
  examples/nestjs/test/book.service.spec.ts
  examples/yoga/src/main.ts
  examples/yoga/src/server.ts
  examples/yoga/test/index.spec.ts
  package.json
  packages/plugins/block-field-suggestions/package.json
  packages/plugins/block-field-suggestions/test/index.spec.ts
  packages/plugins/character-limit/README.md
  packages/plugins/character-limit/package.json
  packages/plugins/character-limit/src/index.ts
  packages/plugins/character-limit/test/index.spec.ts
  packages/plugins/cost-limit/package.json
  packages/plugins/cost-limit/src/index.ts
  packages/plugins/cost-limit/test/index.spec.ts
  packages/plugins/max-aliases/package.json
  packages/plugins/max-aliases/test/index.spec.ts
  packages/plugins/max-depth/package.json
  packages/plugins/max-depth/src/index.ts
  packages/plugins/max-depth/test/index.spec.ts
  packages/plugins/max-directives/package.json
  packages/plugins/max-directives/test/index.spec.ts
  yarn.lock
Labels: enhancement

#86 tests/integration
  examples/apollo/src/server.ts
  examples/apollo/test/index.spec.ts
  examples/yoga/test/index.spec.ts
  package.json
  packages/graphql-armor/src/apollo/protections/block-field-suggestion.ts
  packages/graphql-armor/src/apollo/protections/character-limit.ts
  packages/graphql-armor/test/apollo/armor.spec.ts
  packages/graphql-armor/test/envelop/armor.spec.ts
  packages/plugins/cost-limit/src/index.ts
  packages/plugins/cost-limit/test/index.spec.ts
  packages/plugins/max-aliases/test/index.spec.ts
  packages/plugins/max-depth/src/index.ts
  packages/plugins/max-depth/test/index.spec.ts
  packages/plugins/max-directives/src/index.ts
  packages/plugins/max-directives/test/index.spec.ts
Labels: enhancement

#108 feat: plugins must provide a default configuration
  .changeset/grumpy-bats-nail.md
  examples/apollo/src/server.ts
  packages/graphql-armor/src/apollo/protections/character-limit.ts
  packages/graphql-armor/src/apollo/protections/cost-limit.ts
  packages/graphql-armor/src/apollo/protections/max-aliases.ts
  packages/graphql-armor/src/apollo/protections/max-depth.ts
  packages/graphql-armor/src/apollo/protections/max-directives.ts
  packages/graphql-armor/src/config.ts
  packages/graphql-armor/src/envelop/protections/character-limit.ts
  packages/graphql-armor/src/envelop/protections/cost-limit.ts
  packages/graphql-armor/src/envelop/protections/max-aliases.ts
  packages/graphql-armor/src/envelop/protections/max-depth.ts
  packages/graphql-armor/src/envelop/protections/max-directives.ts
  packages/plugins/block-field-suggestions/README.md
  packages/plugins/block-field-suggestions/src/index.ts
  packages/plugins/character-limit/src/index.ts
  packages/plugins/character-limit/test/index.spec.ts
  packages/plugins/cost-limit/src/index.ts
  packages/plugins/cost-limit/test/index.spec.ts
  packages/plugins/max-aliases/src/index.ts
  packages/plugins/max-aliases/test/index.spec.ts
  packages/plugins/max-depth/src/index.ts
  packages/plugins/max-depth/test/index.spec.ts
  packages/plugins/max-directives/src/index.ts
  packages/plugins/max-directives/test/index.spec.ts
Labels: enhancement, apollo, envelop

#112 Fix(depth limit)/allow introspection
  examples/apollo/src/server.ts
  examples/apollo/test/index.spec.ts
  examples/yoga/package.json
  examples/yoga/test/index.spec.ts
  packages/graphql-armor/package.json
  packages/plugins/cost-limit/test/index.spec.ts
  packages/plugins/max-depth/package.json
  packages/plugins/max-depth/src/index.ts
  packages/plugins/max-depth/test/index.spec.ts
  yarn.lock
Labels: bug, enhancement

#114 test: e2e yoga
  examples/yoga/src/schema.ts
  examples/yoga/src/server.ts
  examples/yoga/test/index.spec.ts
  packages/graphql-armor/src/envelop/armor.ts
Labels: enhancement, envelop

#148 chore(plugins): type statement consistency
  packages/plugins/max-depth/src/index.ts
  packages/plugins/max-directives/src/index.ts
Labels: enhancement
